# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_char_bboxes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ontract_char_bboxes.proto\"!\n\x0b\x43oordinates\x12\x12\n\x06\x63oords\x18\x01 \x03(\x02\x42\x02\x10\x01\"H\n\nCharBboxes\x12!\n\x0b\x63har_bboxes\x18\x01 \x03(\x0b\x32\x0c.Coordinates\x12\x17\n\x0f__initialised__\x18\x02 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contract_char_bboxes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COORDINATES.fields_by_name['coords']._options = None
  _COORDINATES.fields_by_name['coords']._serialized_options = b'\020\001'
  _COORDINATES._serialized_start=30
  _COORDINATES._serialized_end=63
  _CHARBBOXES._serialized_start=65
  _CHARBBOXES._serialized_end=137
# @@protoc_insertion_point(module_scope)
