import logging
import os
import subprocess
import tempfile
from contextlib import contextmanager
from subprocess import CompletedProcess
from typing import Generator

log = logging.getLogger(__name__)


class ConvertToPDFFailed(Exception):
    pass


class OutputPDFDoesNotExistAfterConversion(ConvertToPDFFailed):
    pass


class InputFileDoesNotExist(ConvertToPDFFailed):
    pass


@contextmanager
def convert_to_pdf(src_fn: str) -> Generator[str, None, None]:
    """
    Converts the specified file to pdf using Libre Office CLI.
    Libre Office allows specifying the output directory and does not allow specifying the output file name.
    The output file name is generated by changing the extension to ".pdf".
    To avoid file name conflicts and additional operations the output file is written into
    a temporary directory and next yielded to the caller.
    After returning from the yield the output file and the output temp directory are removed.
    """
    if not os.path.isfile(src_fn):
        raise InputFileDoesNotExist(src_fn)
    temp_dir = tempfile.mkdtemp()
    src_fn_base = os.path.basename(src_fn)
    src_fn_base, src_ext = os.path.splitext(src_fn_base)
    out_fn = os.path.join(temp_dir, src_fn_base + '.pdf')
    try:
        if src_ext.lower() in {'.tiff', '.jpg', '.jpeg', '.png'}:
            completed_process: CompletedProcess = subprocess.run(['img2pdf',
                                                                  src_fn,
                                                                  '-o',
                                                                  out_fn],
                                                                 check=True,
                                                                 text=True,
                                                                 capture_output=True,
                                                                 timeout=600)
        else:
            completed_process: CompletedProcess = subprocess.run(['soffice',
                                                                  '--headless',
                                                                  '--invisible',
                                                                  '--nodefault',
                                                                  '--view',
                                                                  '--nolockcheck',
                                                                  '--nologo',
                                                                  '--norestore',
                                                                  '--nofirststartwizard',
                                                                  '--convert-to',
                                                                  'pdf',
                                                                  src_fn,
                                                                  '--outdir',
                                                                  temp_dir
                                                                  ], check=True, timeout=600, text=True,
                                                                 capture_output=True)
        log.info(completed_process.stdout)
        if completed_process.stderr:
            log.error(completed_process.stderr)
        if not os.path.isfile(out_fn):
            raise OutputPDFDoesNotExistAfterConversion()
        yield out_fn
    finally:
        os.remove(out_fn)
        os.rmdir(temp_dir)
