metadata_fn = 'metadata.json'
results_fn = 'results.zip'
pages_for_ocr = 'pages_for_ocr'
pages_ocred = 'pages_ocred'
pages_pre_processed = 'pages_pre_processed'
from_original_doc = 'from_original_doc.pickle'
task_ids = 'task_ids'
